export const REQUEST_SENT = 'REQUEST_SENT';
export const START_FETCHING = 'START_FETCHING';
export const FETCH_ENTRIES = 'FETCH_ENTRIES';
export const SHOW_LOADER = 'SHOW_LOADER';
export const SORT_ENTRIES = 'SORT_ENTRIES';
export const ASCENDING_ORDER = 'ASCENDING_ORDER';
export const DESCENDING_ORDER = 'DESCENDING_ORDER';
